- name: Multiplay 
  hosts: localhost 
  tasks:
  - name: From PLAY-1
    ansible.builtin.debug:
      msg: "Hello from PLAY-1"

  - name: From PLAY-2 
    ansible.builtin.debug:
      msg: "Hello from PLAY-2"
